using System;
using System.Collections.Generic;

namespace PhuLongCRM.Models
{
    public class MaQuocGiaData
    {
        public static List<MaQuocGia> GetList()
        {

            return new List<MaQuocGia>()
            {
                new MaQuocGia("Vietnam","84"),
                new MaQuocGia("United States","1"),
                new MaQuocGia("Afghanistan","93"),
                new MaQuocGia("Albania","355"),
                new MaQuocGia("Algeria","213"),
                new MaQuocGia("American Samoa","1-684"),
                new MaQuocGia("Andorra","376"),
                new MaQuocGia("Angola","244"),
                new MaQuocGia("Anguilla","1-264"),
                new MaQuocGia("Antarctica","672"),
                new MaQuocGia("Antigua and Barbuda","1-268"),
                new MaQuocGia("Argentina","54"),
                new MaQuocGia("Armenia","374"),
                new MaQuocGia("Aruba","297"),
                new MaQuocGia("Australia","61"),
                new MaQuocGia("Austria","43"),
                new MaQuocGia("Azerbaijan","994"),
                new MaQuocGia("Bahamas","1-242"),
                new MaQuocGia("Bahrain","973"),
                new MaQuocGia("Bangladesh","880"),
                new MaQuocGia("Barbados","1-246"),
                new MaQuocGia("Belarus","375"),
                new MaQuocGia("Belgium","32"),
                new MaQuocGia("Belize","501"),
                new MaQuocGia("Benin","229"),
                new MaQuocGia("Bermuda","1-441"),
                new MaQuocGia("Bhutan","975"),
                new MaQuocGia("Bolivia","591"),
                new MaQuocGia("Bosnia and Herzegovina","387"),
                new MaQuocGia("Botswana","267"),
                new MaQuocGia("Brazil","55"),
                new MaQuocGia("British Indian Ocean Territory","246"),
                new MaQuocGia("British Virgin Islands","1-284"),
                new MaQuocGia("Brunei","673"),
                new MaQuocGia("Bulgaria","359"),
                new MaQuocGia("Burkina Faso","226"),
                new MaQuocGia("Burundi","257"),
                new MaQuocGia("Cambodia","855"),
                new MaQuocGia("Cameroon","237"),
                new MaQuocGia("Canada","1"),
                new MaQuocGia("Cape Verde","238"),
                new MaQuocGia("Cayman Islands","1-345"),
                new MaQuocGia("Central African Republic","236"),
                new MaQuocGia("Chad","235"),
                new MaQuocGia("Chile","56"),
                new MaQuocGia("China","86"),
                new MaQuocGia("Christmas Island","61"),
                new MaQuocGia("Cocos Islands","61"),
                new MaQuocGia("Colombia","57"),
                new MaQuocGia("Comoros","269"),
                new MaQuocGia("Cook Islands","682"),
                new MaQuocGia("Costa Rica","506"),
                new MaQuocGia("Croatia","385"),
                new MaQuocGia("Cuba","53"),
                new MaQuocGia("Curacao","599"),
                new MaQuocGia("Cyprus","357"),
                new MaQuocGia("Czech Republic","420"),
                new MaQuocGia("Democratic Republic of the Congo","243"),
                new MaQuocGia("Denmark","45"),
                new MaQuocGia("Djibouti","253"),
                new MaQuocGia("Dominica","1-767"),
                new MaQuocGia("Dominican Republic","1-829"),
                new MaQuocGia("Dominican Republic","1-809"),
                new MaQuocGia("Dominican Republic","1-849"),
                new MaQuocGia("East Timor","670"),
                new MaQuocGia("Ecuador","593"),
                new MaQuocGia("Egypt","20"),
                new MaQuocGia("El Salvador","503"),
                new MaQuocGia("Equatorial Guinea","240"),
                new MaQuocGia("Eritrea","291"),
                new MaQuocGia("Estonia","372"),
                new MaQuocGia("Ethiopia","251"),
                new MaQuocGia("Falkland Islands","500"),
                new MaQuocGia("Faroe Islands","298"),
                new MaQuocGia("Fiji","679"),
                new MaQuocGia("Finland","358"),
                new MaQuocGia("France","33"),
                new MaQuocGia("French Polynesia","689"),
                new MaQuocGia("Gabon","241"),
                new MaQuocGia("Gambia","220"),
                new MaQuocGia("Georgia","995"),
                new MaQuocGia("Germany","49"),
                new MaQuocGia("Ghana","233"),
                new MaQuocGia("Gibraltar","350"),
                new MaQuocGia("Greece","30"),
                new MaQuocGia("Greenland","299"),
                new MaQuocGia("Grenada","1-473"),
                new MaQuocGia("Guam","1-671"),
                new MaQuocGia("Guatemala","502"),
                new MaQuocGia("Guernsey","44-1481"),
                new MaQuocGia("Guinea","224"),
                new MaQuocGia("Guinea-Bissau","245"),
                new MaQuocGia("Guyana","592"),
                new MaQuocGia("Haiti","509"),
                new MaQuocGia("Honduras","504"),
                new MaQuocGia("Hong Kong","852"),
                new MaQuocGia("Hungary","36"),
                new MaQuocGia("Iceland","354"),
                new MaQuocGia("India","91"),
                new MaQuocGia("Indonesia","62"),
                new MaQuocGia("Iran","98"),
                new MaQuocGia("Iraq","964"),
                new MaQuocGia("Ireland","353"),
                new MaQuocGia("Isle of Man","44-1624"),
                new MaQuocGia("Israel","972"),
                new MaQuocGia("Italy","39"),
                new MaQuocGia("Ivory Coast","225"),
                new MaQuocGia("Jamaica","1-876"),
                new MaQuocGia("Japan","81"),
                new MaQuocGia("Jersey","44-1534"),
                new MaQuocGia("Jordan","962"),
                new MaQuocGia("Kazakhstan","7"),
                new MaQuocGia("Kenya","254"),
                new MaQuocGia("Kiribati","686"),
                new MaQuocGia("Kosovo","383"),
                new MaQuocGia("Kuwait","965"),
                new MaQuocGia("Kyrgyzstan","996"),
                new MaQuocGia("Laos","856"),
                new MaQuocGia("Latvia","371"),
                new MaQuocGia("Lebanon","961"),
                new MaQuocGia("Lesotho","266"),
                new MaQuocGia("Liberia","231"),
                new MaQuocGia("Libya","218"),
                new MaQuocGia("Liechtenstein","423"),
                new MaQuocGia("Lithuania","370"),
                new MaQuocGia("Luxembourg","352"),
                new MaQuocGia("Macau","853"),
                new MaQuocGia("Madagascar","261"),
                new MaQuocGia("Malawi","265"),
                new MaQuocGia("Malaysia","60"),
                new MaQuocGia("Maldives","960"),
                new MaQuocGia("Mali","223"),
                new MaQuocGia("Malta","356"),
                new MaQuocGia("Marshall Islands","692"),
                new MaQuocGia("Mauritania","222"),
                new MaQuocGia("Mauritius","230"),
                new MaQuocGia("Mayotte","262"),
                new MaQuocGia("Mexico","52"),
                new MaQuocGia("Micronesia","691"),
                new MaQuocGia("Moldova","373"),
                new MaQuocGia("Monaco","377"),
                new MaQuocGia("Mongolia","976"),
                new MaQuocGia("Montenegro","382"),
                new MaQuocGia("Montserrat","1-664"),
                new MaQuocGia("Morocco","212"),
                new MaQuocGia("Mozambique","258"),
                new MaQuocGia("Myanmar","95"),
                new MaQuocGia("Namibia","264"),
                new MaQuocGia("Nauru","674"),
                new MaQuocGia("Nepal","977"),
                new MaQuocGia("Netherlands","31"),
                new MaQuocGia("Netherlands Antilles","599"),
                new MaQuocGia("New Caledonia","687"),
                new MaQuocGia("New Zealand","64"),
                new MaQuocGia("Nicaragua","505"),
                new MaQuocGia("Niger","227"),
                new MaQuocGia("Nigeria","234"),
                new MaQuocGia("Niue","683"),
                new MaQuocGia("North Korea","850"),
                new MaQuocGia("Northern Mariana Islands","1-670"),
                new MaQuocGia("Norway","47"),
                new MaQuocGia("Oman","968"),
                new MaQuocGia("Pakistan","92"),
                new MaQuocGia("Palau","680"),
                new MaQuocGia("Palestine","970"),
                new MaQuocGia("Panama","507"),
                new MaQuocGia("Papua New Guinea","675"),
                new MaQuocGia("Paraguay","595"),
                new MaQuocGia("Peru","51"),
                new MaQuocGia("Philippines","63"),
                new MaQuocGia("Pitcairn","64"),
                new MaQuocGia("Poland","48"),
                new MaQuocGia("Portugal","351"),
                new MaQuocGia("Puerto Rico","1-787"),
                new MaQuocGia("Puerto Rico","1-939"),
                new MaQuocGia("Qatar","974"),
                new MaQuocGia("Republic of the Congo","242"),
                new MaQuocGia("Reunion","262"),
                new MaQuocGia("Romania","40"),
                new MaQuocGia("Russia","7"),
                new MaQuocGia("Rwanda","250"),
                new MaQuocGia("Saint Barthelemy","590"),
                new MaQuocGia("Saint Helena","290"),
                new MaQuocGia("Saint Kitts and Nevis","1-869"),
                new MaQuocGia("Saint Lucia","1-758"),
                new MaQuocGia("Saint Martin","590"),
                new MaQuocGia("Saint Pierre and Miquelon","508"),
                new MaQuocGia("Saint Vincent and the Grenadines","1-784"),
                new MaQuocGia("Samoa","685"),
                new MaQuocGia("San Marino","378"),
                new MaQuocGia("Sao Tome and Principe","239"),
                new MaQuocGia("Saudi Arabia","966"),
                new MaQuocGia("Senegal","221"),
                new MaQuocGia("Serbia","381"),
                new MaQuocGia("Seychelles","248"),
                new MaQuocGia("Sierra Leone","232"),
                new MaQuocGia("Singapore","65"),
                new MaQuocGia("Sint Maarten","1-721"),
                new MaQuocGia("Slovakia","421"),
                new MaQuocGia("Slovenia","386"),
                new MaQuocGia("Solomon Islands","677"),
                new MaQuocGia("Somalia","252"),
                new MaQuocGia("South Africa","27"),
                new MaQuocGia("South Korea","82"),
                new MaQuocGia("South Sudan","211"),
                new MaQuocGia("Spain","34"),
                new MaQuocGia("Sri Lanka","94"),
                new MaQuocGia("Sudan","249"),
                new MaQuocGia("Suriname","597"),
                new MaQuocGia("Svalbard and Jan Mayen","47"),
                new MaQuocGia("Swaziland","268"),
                new MaQuocGia("Sweden","46"),
                new MaQuocGia("Switzerland","41"),
                new MaQuocGia("Syria","963"),
                new MaQuocGia("Taiwan","886"),
                new MaQuocGia("Tajikistan","992"),
                new MaQuocGia("Tanzania","255"),
                new MaQuocGia("Thailand","66"),
                new MaQuocGia("Togo","228"),
                new MaQuocGia("Tokelau","690"),
                new MaQuocGia("Tonga","676"),
                new MaQuocGia("Trinidad and Tobago","1-868"),
                new MaQuocGia("Tunisia","216"),
                new MaQuocGia("Turkey","90"),
                new MaQuocGia("Turkmenistan","993"),
                new MaQuocGia("Turks and Caicos Islands","1-649"),
                new MaQuocGia("Tuvalu","688"),
                new MaQuocGia("U.S. Virgin Islands","1-340"),
                new MaQuocGia("Uganda","256"),
                new MaQuocGia("Ukraine","380"),
                new MaQuocGia("United Arab Emirates","971"),
                new MaQuocGia("United Kingdom","44"),
                new MaQuocGia("Uruguay","598"),
                new MaQuocGia("Uzbekistan","998"),
                new MaQuocGia("Vanuatu","678"),
                new MaQuocGia("Vatican","379"),
                new MaQuocGia("Venezuela","58"),
                new MaQuocGia("Wallis and Futuna","681"),
                new MaQuocGia("Western Sahara","212"),
                new MaQuocGia("Yemen","967"),
                new MaQuocGia("Zambia","260"),
                new MaQuocGia("Zimbabwe","263"),

            };
        }
    }
}
